name: CI/CD Deploy

on:
  workflow_dispatch:  # позволяет запускать GitHub Actions вручную из GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /
          cd /projects/AdvertisingBoard/client
          git clone https://github.com/Batonrain/bus-adv-client.git
          cd bus-adv-client
          ng dist
          # git pull origin main
          # rm rf dist/*
          


